Replace deprecated `recommonmark` with MyST-Parser
dry-python/returns pull request #1089
Opened 2021-10-01 07:26 UTC by radiantly

Docs generation now uses `MyST-Parser` instead of the deprecated `recommonmark` to parse .md files.

Other changes:
 - removed m2r package as it is no longer required
 - remove monkey patches relating to m2r
 - bump copyright year to 2021

# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #1082

2021-10-01 08:00 UTC, sobolevn requested changes
Thanks! We also need to remove this from `pyproject.toml` and `poetry.lock`

2021-10-01 12:40 UTC, radiantly commented
Done, but I think there's a bit of an issue when running `doc8` - however, sphinx builds perfectly, so I'm not sure what exactly the problems is.

2021-10-01 12:56 UTC, sobolevn approved these changes
Thanks!

2023-04-11 19:52 UTC, thepabloaguilar commented
Closing this PR since #1082 have been resolved!

2023-04-11 19:52 UTC, closed without merging